
items = {"potion": {"name": "General potion of nothingness",
                    'grounddesc': "potion description on the ground",
                         'shortdesc': "potion short description",
                         'longdesc': "potion long description",
                         'takeable': True,
                         'edible': True,
                         'value': 1,
                         'descwords': ['potion']
                         },
              "stone": {'grounddesc': "stone description on the ground",
                         'shortdesc': "stone short description",
                         'longdesc': "stone long description",
                         'takeable': True,
                         'edible': False,
                         'value': 0,
                         'descwords': ['stone', 'rock']
                         },
              "gold": {'grounddesc': "gold description on the ground",
                        'shortdesc': "gold short description",
                        'longdesc': "gold long description",
                        'takeable': True,
                        'descwords': ['gold', 'coin'],
                        'value': 1,
                        },
			 "shield": {'grounddesc': "shield ground description.",
			            'shortdesc': "shield short description",
						'longdesc': "shield long description",
						'descwords': ['shield'],
						'takeable': True,
                        'type': 'armour',
						'slot': ['lhand'],
						'value': 5,
						'bonus': 2},
			 "sword": {'grounddesc': "sword ground description.",
			            'shortdesc': "sword short description",
						'longdesc': "sword long description",
                        'descwords': ['sword'],
						'takeable': True,
						'type': 'weapon',
						'slot': ['rhand'],
						'value': 3,
						'bonus': 1},
}