
rooms = {'v1': {'name': "Main square",
                'initial_desc': "initial description of main square",
                'desc': "look description of main square. This is more or less the center of the village. This is just some text to test the textwrap functionality for the description of locations. The text cannot be on a second line in the dictionary. I wonder if this will all look rather ok in the command line.",
                'ground': ['gold', 'stone'],
                'npcs': [],
                "monsters": [],
                "events": [],
                'n': "v6",
                "e": "v3",
                "w": "v7",
                "s": "v5"},
         'v2': {'name': "Apothecary",
                'desc': "A longer description of the Apothecary. To see how it is going to workout for shops that have more information in the display compared to other locations.",
                'ground': [],
                'npcs': ['greg'],
                'monsters': [],
                'shop': ['potion'],
                "events": [],
                "w": "v6"},
         'v3': {'name': "Sandbox",
                'desc': "Here anything can happen for testing purposes.",
                'ground': [],
                'npcs': [],
                'monsters': ["small orc warrior", "big troll", "big orc warrior"],
                "events": ["combat"],
                'w': "v1"},
         'v4': {'name': "Blacksmith",
                'desc': "The place for adventuring equipment",
                'ground': [],
                'npcs': [],
                'monsters': [],
                'shop': ["sword"],
                "events": [],
                'e': "v6"},
         'v5': {'name': "Gate street",
                'desc': "The street leading from the town gate to the main square",
                'ground': [],
                'npcs': [],
                'monsters': [],
                "events": [],
                "n": "v1"},
         'v6': {'name': "North street",
                'desc': "The street leading from the town square to the housing area",
                'ground': [],
                'npcs': [],
                'monsters': [],
                "events": [],
                "s": "v1",
                "e": "v2",
                "w": "v4"},
         'v7': {'name': "West street",
                'desc': "The street leading from the town square to the housing area",
                'ground': [],
                'npcs': [],
                'monsters': [],
                "shop": [],
                "events": [],
                "e": "v1",
                "s": "v8_door1"},
         'v8': {'name': "Locked house",
                'desc': "a house with a locked front door.",
                'ground': [],
                'npcs': [],
                'monsters': [],
                "events": [],
                "e": "v1",
                "n": "v8_door1"},
         'v8_door1': {'name': "Oak door",
                      'desc': "a solid oak door with a lock.",
                      "locked": True,
                      'ground': [],
                      'npcs': [],
                      "events": [],
                      "n": "v7",
                      "s": "v8"},
         }
